# Generated by Django 3.1.6 on 2021-02-15 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0003_auto_20210215_2015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reference',
            name='slug',
        ),
    ]
