# Generated by Django 3.1.6 on 2021-02-15 18:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0006_auto_20210215_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='reference',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='reference',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
