# Generated by Django 3.1.6 on 2021-02-16 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0007_auto_20210215_2035'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=15)),
                ('shortcut', models.CharField(max_length=2)),
                ('currency', models.CharField(max_length=3)),
            ],
        ),
        migrations.AlterField(
            model_name='reference',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsite.region'),
        ),
    ]
