# Generated by Django 3.1.6 on 2021-02-18 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0008_auto_20210216_0424'),
    ]

    operations = [
        migrations.AddField(
            model_name='reference',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
